### ISSUE TITLE
[Feature Request] Add BasicChatMods Compatibility to Fade In

### ISSUE THREAD

**Issue by Hayato2846** [ls-/ls_Glass#14]
Hello!
First of all: Thank you so much for your addon. I really love it!

I'm not sure if that's a thing on LS: Glass' or BasicChatMods' site but there's currently some unbeautiful behavior between fading in new messages and chat formatting provided by BasicChatMods.

Example:
https://streamable.com/9hacot

It seems like formatting is applied after the fade in animation has finished.

Thanks in advance :)

**Comment by ls-** [comment]
Hi :>

This behaviour is expected due to how chat addons work, we all independently hook up to the same stuff and then process it on our end. That's why this kind of desyncs happen. I'll look into what BCM is doing and if it's possible to tap into it without too much pain in my butt on my end, but I also have plans for my own text processing eventually, but they aren't a high prio for me atm.

**Comment by ls-** [comment]
As expected funkydude and his addons, it's pretty straightforward. I'll try some stuff out later.

**Comment by ls-** [comment]
I lied, after checking that stuff our closer, none of his functions are actually exposed, so it's impossible for me to hook up to it.

**Comment by ls-** [comment]
But there's a workaround for that, I think...

**Comment by ls-** [comment]
![processing text](https://user-images.githubusercontent.com/2725970/201559264-19c339e3-8e29-4c19-bda0-a069246181f6.gif)

K, this should do the trick, I changed where I'm pulling the data from, so it should be more compatible with text processing done by other chat addons 😊
