### ISSUE TITLE
[Feature Request] Option for Uniform, Fixed-Height Chat Lines

### ISSUE THREAD

**Issue by xRaen** [ls-/ls_Glass#21]
Something that really drives me crazy with WoW chat and that still happens in Glass is that not all lines in the chat are a fixed height, which leads to some lines getting cut off at the top of the chat window. Even when turning vertical padding down to the minimum of 1, a number of things break the uniformity, namely messages that take multiple line, messages with ability icons in them, loot messages, and probably more I'm not thinking of right now. 

If possible, I'd love an option to always ensure every line is a uniform height so that no lines ever get cut off.

**Comment by ls-** [comment]
I can't do that because the height depends on the height of the message string after it gets wrapped and whatnot to fit the width of the chat frame. If I were to limit the height artificially 2 things will happen: if it's too big, you'll get massive gaps for shorter messages; if it's not big enough, longer messages will turn into `...`.
You're honestly complaining about super standard chat behaviour, when I open my DMs on insta, I see "cut off" chat bubbles, the same goes for discord, etc.
