### ISSUE TITLE
[Suggestion] Messages - Vertical padding of 0 as an option.

### ISSUE THREAD

**Issue by ghost** [ls-/ls_Glass#27]
Hello,

Was wondering if you could add an option to have 0 vertical padding (currently restricted at 1) to mimic the default chat.
I'm trying to make it match the combat log, but it seems to have a vertical padding of 0.

Thank you!! :)

**Comment by JBabbb** [comment]
EDIT: unless somehow you could make the combat log like the other tabs... but that's probably not possible :P

**Comment by ls-** [comment]
Iirc, due to how the whole scrolling thing was implemented I kinda had to set the minimum to `1px`, originally it's `0px`. The thing is, in WoW these coordinates are never actually `0`, there's no integers, only floats, so when you set something to `0` it's actually `0.000000001561` or something. In turn you get pretty funky behaviour depending on what you're doing. I'll look into it later, but I'm not sure... 😵

Truth be told, I'm still not sure what I wanna do with the combat log. I can't add smooth scrolling to it because of how much stuff gets pushed to that frame. Like, chat performance in WoW isn't great to begin with, you add fancy scrolling on top of that, and you get even less FPS >_> That's one of the reason why I added [the third point to my F&Q](https://github.com/ls-/ls_Glass#faq), in the past some people in my discord started fearmongering without understanding what's actually going on 😒 So if I were you, I'd refrain from keeping the combat log shown at all times 😓

**Comment by JBabbb** [comment]
I understand! I've been using leatrix plus and hiding the combat log and it works fine, don't stress it too much.

**Comment by ls-** [comment]
This one was properly fixed in `100206.x, I just completely forgot about the opened issue. So it's safe to close it now 😅

TomCats is no longer Canadian ~a south park ref~ :D
![image](https://github.com/ls-/ls_Glass/assets/2725970/ee03852e-9e80-46f3-bc09-33e67a6876ac)
