### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by ghost** [ls-/ls_Glass#28]
Hello, I really like this addon!
Could you please consider:

1. Fading out 'social' button
![image](https://user-images.githubusercontent.com/122007087/236582031-2c04a93a-2766-4c12-82c4-87b220bff833.png)

2. Customize fadeout time of tabs
For example i want my tabs to appear and disappear instantly on mouseover. No delay.

Thank you :)

**Comment by ls-** [comment]
Hi!

> Fading out 'social' button

I'll do something about the "Social" button soon™, I'm currently rewriting the addon 🤔 For now use an addon like BasicChatMods.

> Customize fadeout time of tabs

This is honestly a massive pita and a can of worms I'm not willing to open. Fading of the tabs is controlled by Blizz, and I can't adjust that stuff at all because it'll break the default UI, I tried. What I ended up doing in glass is I basically wait until Blizz are done fading on their end, and then I fade them out for good. It's basically double fading, it's annoying even for me, but it is what it is 😭

**Comment by ls-** [comment]
As I said in another issue I just close, this one is coming with TWW. I rewrote the whole thing and finally hooked and gutted that social button and the whole chat alert system.

![glass_button_fading](https://github.com/ls-/ls_Glass/assets/2725970/38eda854-f020-4dc3-ac3f-c3d20213e3bd)

![image](https://github.com/ls-/ls_Glass/assets/2725970/6c705a58-2403-4546-a172-fa33b63dc443)

Closing.
