### ISSUE TITLE
Switching chat tabs breaks the chat in 10.2.6

### ISSUE THREAD

**Issue by NoShotz** [ls-/ls_Glass#34]
If you switch chat tabs, the chat in said tabs will now be completely blank, no amount of switching chat tabs fixes the issue.

**Comment by cleanlock** [comment]
Yup, got the same issue.

**Comment by icenix2024** [comment]
Experiencing the same.

**Comment by Crolo01** [comment]
yep, true and real

**Comment by robbentenmann** [comment]
Has there been a solution found for fixing the chat tab breaking since the new patch? Its not happening in classic wrath so it has to do with retail and 10.2.6 only.

**Comment by ArenfeIdt** [comment]
It is probably happening because Plunderstorm is in the exact same Client — disabling Addons like that seems to cause some problems.

For example — i do not see the Blizzard Damage Numbers because of Classic FCT.

So i assume it works the same way for the Chat — as there are no different Chat Tabs in Plunderstorm.

**Comment by Greylight1180** [comment]
Having the same same issues 10.2.6

**Comment by V1rtuou5** [comment]
Same, after switching tabs the text field stays blank as of 10.2.6

**Comment by ls-** [comment]
This and a few other issues were fixed in [the latest update](https://github.com/ls-/ls_Glass/releases/tag/100206.01).

Blizz broke a bunch of things in 10.2.6 because they had to add/update a bunch of things because of Plunderstorm. They had to move things around and whatnot because the code for chat and many other things is shared between the two game modes. I patched what's broken and backported a couple of fixes from the planned rewrite of the addon, so it should be fine for the time being.

That said, I'm not really back to working on this addon or any other of my addons for that matter. I had a couple of surgeries in Feb. And I'm currently undergoing chemotherapy that I started earlier this month, so I'm like a half-veggie. The brain fog is no fun. I'm still not sure if I want to make a proper announcement about it.

**Comment by icenix2024** [comment]
Thank you Val for the update on both the add-on and your personal situation.  while lesser important of the two, the addon is functioning as expected again. Feel free to delete this if you'd decide to remove disclosure of the second.

**Comment by cleanlock** [comment]
@ls- thank you for the update. I wish you a lot of strength and get well soon!

**Comment by Crolo01** [comment]
thank you for this wonderful addon
wish you the best <3

**Comment by robbentenmann** [comment]
Thank you so much for fixing the issue and for the addon @ls- 
Hope you get well soon and things improve <3

**Comment by ls-** [comment]
Thanks for understanding. And stay healthy, being sick is no fun at all.
