### ISSUE TITLE
[Feature Request] Input box fading

### ISSUE THREAD

**Issue by Baz4k** [ls-/ls_Glass#38]
I would love if the input box faded as well. I know that I can change the transparency, but I still would like it there when I am typing. 

Awesome work btw, its in my Mount Rushmore of mandatory addons. All of your work is appreciated!

**Comment by ls-** [comment]
If you don't want to see the input box, you should switch to the classic chat mode, the im mode has that permanent half-faded edit box on the screen. It's in Blizz config, iirc, esc > options > social, and then scroll down, you'll see a bunch of chat options there.

I actually tried adding fading to the edit box during my rewrite, but the whole edit box thingy is so weirdly written on blizz end, in part because there's two chat styles that have very different edit box behaviour, that I chose not to do it. It's a can of worms I'm not willing to open. Sorry about that.
