### ISSUE TITLE
WoW Cataclysm - CreateUnsecuredObjectPool is nil

### ISSUE THREAD

**Issue by siegester03** [ls-/ls_Glass#42]
Any chance for classic support? CreateUnsecuredObjectPool doesn't exist (and is in 2 files), but CreateObjectPool works. Any chance on adding some game client version detection to support this?

**Comment by ls-** [comment]
Ugh, it's a sensitive topic.

I don't play classic at all, so I avoid adding classic support to my addons. Toasts are the only exception because initially it's pretty easy to implement for vanilla, tbc, and kinda wotlk, but, ngl, even that's gotten pretty annoying lately because the state of classic API is a complete mess, updating that addon for cata was a royal pita.

For this reason I want to stick to just retail for the rest of my addons.
